name: Test on Node.js

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v3
    - name: Use default Node.js for ${{ matrix.os }}
      uses: actions/setup-node@v3

    - run: npm install

    - run: npm test
      if: matrix.os != 'windows-latest'

    # npm test calls eslint and nyc
    # On windows eslint fails because of lineends
    # nyc fails due to
    # Error: Cannot find module 'D:\a\node-shell-quote\node-shell-quote\node'
    - run: ./node_modules/.bin/tape 'test/**/*.js'
      if: matrix.os == 'windows-latest'


    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/coverage-final.json
        fail_ci_if_error: true
        verbose: true
      # there's no coverage on windows because nyc doesn't work
      if: matrix.os != 'windows-latest'
